name: Deploy Admin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make properties file
        run: |
          rm ./admin/src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES_ADMIN }}" > ./admin/src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean :admin:build

      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: admin/build/reports/tests

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: admin/build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: application
          path: deploy

      - name: Generate deployment package
        run: |
          cp deploy/*.jar deploy/application.jar
          cd deploy && zip -r deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ticket-reserve-admin
          environment_name: Ticket-reserve-admin-env
          version_label: ver-${{ github.sha }}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip