name: Deploy Admin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean :admin:build
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          PASSWORD_ENCODER_SECRET: ${{ secrets.PASSWORD_ENCODER_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Rename build file
        run: mv ./admin/build/libs/*.jar ./application.jar

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: application.jar
          target: /home/ubuntu/ticket-reserve/tobe