name: Deploy Admin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make properties file
        run: |
          rm ./admin/src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES_ADMIN }}" > ./admin/src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean :admin:build

      - name: Rename build file
        run: mv ./admin/build/libs/*.jar ./application.jar

      - name: Compress files
        run: tar -czvf $GITHUB_SHA.tar.gz application.jar appspec.yml scripts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://ticket-reserve-admin/$GITHUB_SHA.tar.gz

      - name: Deploy to EC2
        run: aws deploy create-deployment
          --application-name ticket-reserve-admin
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name Production
          --s3-location bucket=ticket-reserve-admin,bundleType=tgz,key=$GITHUB_SHA.tar.gz