name: Deploy Admin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make properties file
        run: |
          rm ./admin/src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES_ADMIN }}" > ./admin/src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean :admin:build

      - name: Rename build file
        run: mv ./admin/build/libs/*.jar ./application.jar

      - name: Copy build file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: application.jar
          target: /home/ubuntu/ticket-reserve/tobe